// templates/nextjs-app/app/page.tsx
'use client';

import { useState } from 'react';
import { useEncrypt } from '@fhevm/sdk/react';
import EncryptForm from '@/components/EncryptForm';
import DecryptDisplay from '@/components/DecryptDisplay';

export default function Home() {
  const [encryptedValue, setEncryptedValue] = useState<any>(null);
  const { isInitialized } = useEncrypt();

  return (
    <main className="min-h-screen bg-gradient-to-br from-blue-50 to-indigo-100 py-12 px-4">
      <div className="max-w-4xl mx-auto">
        {/* Header */}
        <div className="text-center mb-12">
          <h1 className="text-4xl font-bold text-gray-900 mb-4">
            FHEVM SDK Example
          </h1>
          <p className="text-lg text-gray-600 mb-2">
            Next.js 14 Application with Fully Homomorphic Encryption
          </p>
          <div className="flex items-center justify-center gap-2">
            <div className={`h-2 w-2 rounded-full ${isInitialized ? 'bg-green-500' : 'bg-yellow-500'}`} />
            <span className="text-sm text-gray-500">
              {isInitialized ? 'SDK Initialized' : 'Initializing SDK...'}
            </span>
          </div>
        </div>

        {/* Main Content */}
        <div className="grid md:grid-cols-2 gap-8">
          {/* Encryption Section */}
          <div className="bg-white rounded-lg shadow-lg p-6">
            <h2 className="text-2xl font-semibold text-gray-800 mb-4">
              Encrypt Data
            </h2>
            <p className="text-gray-600 mb-6">
              Enter a number to encrypt it using Fully Homomorphic Encryption.
              The encrypted value can be used in smart contracts without revealing the plaintext.
            </p>
            <EncryptForm onEncrypted={setEncryptedValue} />
          </div>

          {/* Decryption Section */}
          <div className="bg-white rounded-lg shadow-lg p-6">
            <h2 className="text-2xl font-semibold text-gray-800 mb-4">
              Decrypt Data
            </h2>
            <p className="text-gray-600 mb-6">
              View the encrypted data and decrypt it if you have the proper permissions.
            </p>
            <DecryptDisplay encryptedValue={encryptedValue} />
          </div>
        </div>

        {/* Features Section */}
        <div className="mt-12 bg-white rounded-lg shadow-lg p-8">
          <h2 className="text-2xl font-semibold text-gray-800 mb-6 text-center">
            Key Features
          </h2>
          <div className="grid md:grid-cols-3 gap-6">
            <div className="text-center">
              <div className="bg-blue-100 rounded-full w-16 h-16 flex items-center justify-center mx-auto mb-4">
                <svg className="w-8 h-8 text-blue-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 15v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2zm10-10V7a4 4 0 00-8 0v4h8z" />
                </svg>
              </div>
              <h3 className="font-semibold text-gray-800 mb-2">FHE Encryption</h3>
              <p className="text-sm text-gray-600">
                Encrypt data that can be computed on without decryption
              </p>
            </div>
            <div className="text-center">
              <div className="bg-green-100 rounded-full w-16 h-16 flex items-center justify-center mx-auto mb-4">
                <svg className="w-8 h-8 text-green-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 10V3L4 14h7v7l9-11h-7z" />
                </svg>
              </div>
              <h3 className="font-semibold text-gray-800 mb-2">Easy Integration</h3>
              <p className="text-sm text-gray-600">
                Simple hooks API with less than 10 lines of code
              </p>
            </div>
            <div className="text-center">
              <div className="bg-purple-100 rounded-full w-16 h-16 flex items-center justify-center mx-auto mb-4">
                <svg className="w-8 h-8 text-purple-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z" />
                </svg>
              </div>
              <h3 className="font-semibold text-gray-800 mb-2">Type Safe</h3>
              <p className="text-sm text-gray-600">
                Full TypeScript support with complete type definitions
              </p>
            </div>
          </div>
        </div>

        {/* Documentation Link */}
        <div className="mt-8 text-center">
          <p className="text-gray-600 mb-4">
            Learn more about the FHEVM SDK and how to build confidential dApps
          </p>
          <a
            href="https://docs.zama.ai/fhevm"
            target="_blank"
            rel="noopener noreferrer"
            className="inline-flex items-center gap-2 text-blue-600 hover:text-blue-700 font-medium"
          >
            View Documentation
            <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10 6H6a2 2 0 00-2 2v10a2 2 0 002 2h10a2 2 0 002-2v-4M14 4h6m0 0v6m0-6L10 14" />
            </svg>
          </a>
        </div>
      </div>
    </main>
  );
}

// examples/vue-app/src/App.vue
<script setup lang="ts">
import { provideFHEVM } from '@fhevm/sdk/vue';
import { computed } from 'vue';

// Initialize FHEVM SDK
const config = {
  contractAddress: import.meta.env.VITE_CONTRACT_ADDRESS || '0x',
  network: import.meta.env.VITE_NETWORK || 'sepolia',
  aclAddress: import.meta.env.VITE_ACL_ADDRESS,
};

const { isInitialized, isInitializing, error } = provideFHEVM(config);

const statusColor = computed(() => {
  if (error.value) return 'bg-red-500';
  if (isInitializing.value) return 'bg-yellow-500';
  if (isInitialized.value) return 'bg-green-500';
  return 'bg-gray-500';
});

const statusText = computed(() => {
  if (error.value) return `Error: ${error.value}`;
  if (isInitializing.value) return 'Initializing SDK...';
  if (isInitialized.value) return 'SDK Ready';
  return 'Not initialized';
});
</script>

<template>
  <div id="app" class="min-h-screen bg-gray-50">
    <!-- Header -->
    <header class="bg-white shadow-sm">
      <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-4">
        <div class="flex items-center justify-between">
          <div>
            <h1 class="text-2xl font-bold text-gray-900">FHEVM SDK</h1>
            <p class="text-sm text-gray-600">Vue 3 Example Application</p>
          </div>
          <div class="flex items-center gap-2">
            <div :class="['h-2 w-2 rounded-full', statusColor]"></div>
            <span class="text-sm text-gray-600">{{ statusText }}</span>
          </div>
        </div>
      </div>
    </header>

    <!-- Main Content -->
    <main class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
      <RouterView v-if="isInitialized" />

      <!-- Loading State -->
      <div v-else-if="isInitializing" class="text-center py-12">
        <div class="inline-block animate-spin rounded-full h-12 w-12 border-b-2 border-blue-600"></div>
        <p class="mt-4 text-gray-600">Initializing FHEVM SDK...</p>
      </div>

      <!-- Error State -->
      <div v-else-if="error" class="bg-red-50 border border-red-200 rounded-lg p-6">
        <div class="flex items-center gap-3">
          <svg class="w-6 h-6 text-red-600" fill="currentColor" viewBox="0 0 20 20">
            <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zM8.707 7.293a1 1 0 00-1.414 1.414L8.586 10l-1.293 1.293a1 1 0 101.414 1.414L10 11.414l1.293 1.293a1 1 0 001.414-1.414L11.414 10l1.293-1.293a1 1 0 00-1.414-1.414L10 8.586 8.707 7.293z" clip-rule="evenodd" />
          </svg>
          <div>
            <h3 class="text-lg font-semibold text-red-900">Failed to Initialize</h3>
            <p class="text-red-700 mt-1">{{ error }}</p>
          </div>
        </div>
      </div>
    </main>

    <!-- Footer -->
    <footer class="bg-white border-t border-gray-200 mt-12">
      <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-6">
        <div class="text-center text-sm text-gray-500">
          <p>Built with FHEVM SDK | Powered by Zama</p>
          <p class="mt-1">
            <a href="https://docs.zama.ai/fhevm" target="_blank" class="text-blue-600 hover:text-blue-700">
              View Documentation
            </a>
          </p>
        </div>
      </div>
    </footer>
  </div>
</template>

<style scoped>
#app {
  font-family: Inter, system-ui, -apple-system, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}
</style>
